version: "3"

services:
  nginx:
    image: nexus/nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx-server
    volumes:
      - nginx-data:/data/nginx
    links:
      - nexus
  nexus:
    image: sonatype/nexus3:latest
    volumes:
      - nexus-data:/nexus-data
    container_name: nexus-server
volumes:
  nexus-data:
    external: true
  nginx-data:
    external: true